<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica Dirigida 6</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Material para pds</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li>
  <a href="pd1.html">Práctica dirigida 1</a>
</li>
<li>
  <a href="pd2.html">Práctica dirigida 2</a>
</li>
<li>
  <a href="pd3.html">Práctica dirigida 3</a>
</li>
<li>
  <a href="pd4.html">Práctica dirigida 4</a>
</li>
<li>
  <a href="pd5.html">Práctica dirigida 5</a>
</li>
<li>
  <a href="pd6.html">Práctica dirigida 6</a>
</li>
<li>
  <a href="pd7.html">Práctica dirigida 7</a>
</li>
<li>
  <a href="pd8.html">Práctica dirigida 8</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica Dirigida 6</h1>

</div>


<p>FACULTAD DE CIENCIAS SOCIALES - PUCP</p>
<p>Curso: SOC294 - Estadística para el análisis sociológico 1</p>
<p>Semestre 2024 - 2</p>
<div id="anova" class="section level2">
<h2><strong>ANOVA</strong></h2>
<p><strong>¿Qué es el Análisis de Varianza (ANOVA)?</strong></p>
<p>Es una prueba estadística que permite comparar la media (promedio) de
<strong>más de 2 grupos</strong>. Es decir, es como una prueba T, pero
de más de dos grupos.</p>
<p>Al igual que con la prueba T, en esta oportunidad debemos observar el
<strong>p-value</strong> de la prueba. Para ello, se establecen 2
hipótesis:</p>
<p>H0 (p-value &gt; 0.05): no hay diferencia significativa entre las
medias de ningún grupo. H1 (p-value =&lt; 0.05): al menos una media
poblacional (de un grupo) es significativamente distinta a las otras</p>
<p><strong>Estadístico F</strong></p>
<p>Indica la variablidad entre grupos y dentro de un mismo grupo.</p>
<p>Si F es grande, hay mucha variabilidad entre grupos y poca
variabilidad dentro de un mismo grupo. Si F es pequeño, hay poca
variabilidad entre grupos pero mucha variabilidad dentro de un mismo
grupo.</p>
<p><strong>Prueba Tukey</strong></p>
<p>Prueba “post-hoc” (luego de), realizada para revisar entre qué grupos
existe una diferencia significativa.</p>
<p>OJO: como es una prueba complementaria a la ANOVA, <strong>solo
resulta necesaria si se rechaza la H0</strong> en ANOVA. Si la H0 no se
rechaza en ANOVA, no hay necesidad de hacer prueba Tukey.</p>
<p>Al igual que las otras pruebas estadísticas, se debe ver el p-value
en cada emparejamiento</p>
<p><img src="Dicpd6.png" /></p>
<pre class="r"><code>library(rio)
data=import(&quot;dataWorld_q.rda&quot;)</code></pre>
<div
id="existe-diferencias-en-la-tasa-de-fecundidad-según-la-quinquenio-entre-el-2000-y-el-2019"
class="section level3">
<h3>¿Existe diferencias en la tasa de fecundidad según la quinquenio
(entre el 2000 y el 2019)?</h3>
<p>Observemos algunos estadísticos descriptivos.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.2.3</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.3     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors</code></pre>
<pre class="r"><code>library(lsr)

library(dplyr)

data &lt;- data %&gt;%
  filter(quinq %in% c(&quot;2000-2004&quot;, &quot;2005-2009&quot;, &quot;2010-2014&quot;, &quot;2015-2019&quot;))


tabla1 = data %&gt;%
  group_by(quinq) %&gt;%
  summarise(Media = mean(tfr, na.rm = T),
            Mediana = median(tfr, na.rm = T),
            Desviacion = sd(tfr, na.rm = T),
            Inferior = ciMean(tfr, na.rm = T)[1],
            Superior = ciMean(tfr, na.rm = T)[2])

tabla1</code></pre>
<pre><code>## # A tibble: 4 × 6
##   quinq     Media Mediana Desviacion Inferior Superior
##   &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 2000-2004  3.25    2.72       1.74     3.00     3.51
## 2 2005-2009  3.08    2.57       1.61     2.84     3.31
## 3 2010-2014  2.93    2.41       1.46     2.72     3.14
## 4 2015-2019  2.79    2.30       1.33     2.59     2.98</code></pre>
<p>Veámoslo en gráficos</p>
<pre class="r"><code>library(ggplot2)
ggplot(tabla1, aes(x=quinq, y=Media, fill = quinq))+
  geom_bar(stat=&quot;identity&quot;)+
  geom_errorbar(aes(ymin=Inferior, ymax=Superior), width=0.2)+
  geom_text(aes(label=paste(round(Media, 1))), vjust=-2, size=3)+
  xlab(&quot;Quinquenio&quot;) + ylab(&quot;Tasa global de fecundidad&quot;)+
  ylim(0, 5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Realicemos un ANOVA</p>
<pre class="r"><code>anova1 = aov(data$tfr ~ data$quinq)
summary(anova1)</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)  
## data$quinq    3   22.2   7.402   3.121 0.0255 *
## Residuals   732 1736.3   2.372                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 40 observations deleted due to missingness</code></pre>
<p>Observamos que el p-value es menor a 0.05, lo que significa que al
menos un grupo tiene la media estadísticamente significativa respecto
del resto.</p>
<p>Para saber qué media es distinta, aplicamos la prueba Tukey.</p>
<pre class="r"><code>comparacion = TukeyHSD(anova1)
comparacion</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = data$tfr ~ data$quinq)
## 
## $`data$quinq`
##                           diff        lwr         upr     p adj
## 2005-2009-2000-2004 -0.1772826 -0.5907450  0.23617975 0.6871398
## 2010-2014-2000-2004 -0.3226739 -0.7361363  0.09078845 0.1853354
## 2015-2019-2000-2004 -0.4687799 -0.8822423 -0.05531753 0.0189101
## 2010-2014-2005-2009 -0.1453913 -0.5588537  0.26807105 0.8019407
## 2015-2019-2005-2009 -0.2914973 -0.7049596  0.12196508 0.2668386
## 2015-2019-2010-2014 -0.1461060 -0.5595683  0.26735638 0.7995750</code></pre>
<p>solo la comparación 2015-2019 vs. 2000-2004 tiene un valor p ajustado
de 0.0189, que es menor que 0.05, lo cual indica que esta diferencia es
estadísticamente significativa.</p>
</div>
</div>
<div id="diagramas-de-dispersión-y-correlación" class="section level2">
<h2><strong>Diagramas de dispersión y correlación</strong></h2>
<div id="ideas-clave" class="section level3">
<h3>Ideas clave</h3>
<p>La correlación es en esencia una medida normalizada de asociación o
covariación lineal entre dos variables.</p>
<ul>
<li><p>La <strong>correlación</strong> es una medida de la relación
(covariación) entre <strong>dos variables
cuantitativas.</strong></p></li>
<li><p>La manera más sencilla de saber si dos variables están
correlacionadas es determinar si co-varían (varían
conjuntamente).</p></li>
<li><p>Es importante hacer notar que <strong>esta covariación o relación
no implica necesariamente causalidad</strong>: La correlación puede ser
fortuita, como en el caso clásico de la correlación entre el número de
venta de helados e incendios, debido al efecto de una tercera variable,
la temperatura ambiental. A este tipo de relación se le llama
“espuria”.</p></li>
</ul>
</div>
<div id="hipótesis-de-la-prueba-de-correlación" class="section level3">
<h3>Hipótesis de la prueba de correlación</h3>
<ul>
<li>H0 : No existe correlación entre las variables</li>
<li>H1 : Existe correlación entre las variables</li>
</ul>
</div>
<div id="coeficiente-de-correlación-de-pearson" class="section level3">
<h3>Coeficiente de Correlación de Pearson</h3>
<ul>
<li><p>“El Coeficiente de Correlación de Pearson es un estadístico
paramétrico, pues se asume que ambas variables tienen una distribución
aproximadamente normal, o sea, distribución normal bivariante”.</p></li>
<li><p>Es una medida que <strong>puede variar entre -1 y +1</strong>,
ambos extremos indicando correlaciones perfectas, negativa y positiva
respectivamente.</p></li>
<li><p>Un valor de r = 0 indica que no existe relación lineal entre las
dos variables.</p></li>
</ul>
<p><img src="G1.png" /></p>
</div>
<div id="gráfico-de-dispersión" class="section level3">
<h3>Gráfico de dispersión</h3>
<p><img src="G2.png" /></p>
<p>Otros ejemplos:</p>
<p><img src="G3.png" /></p>
</div>
<div id="aplicación-práctica" class="section level3">
<h3>Aplicación práctica</h3>
</div>
</div>
<div
id="que-factores-se-relacionan-con-la-tasa-de-fecundidad-en-los-países-entre-los-años-2015-2019"
class="section level1">
<h1>¿Que factores se relacionan con la tasa de fecundidad en los países
entre los años 2015-2019?</h1>
<p>Como vimos anteriormente, nuestra data abarca distintos periodos.
Analicemos los factores que se relacionan con la tasa de fecundidad en
el periodo más reciente: 2015-2019</p>
<p>Primero revisemos como está escrito y luego filtremos</p>
<pre class="r"><code>table(data$quinq)</code></pre>
<pre><code>## 
## 1950-1954 1955-1959 1960-1964 1965-1969 1970-1974 1975-1979 1980-1984 1985-1989 
##         0         0         0         0         0         0         0         0 
## 1990-1994 1995-1999 2000-2004 2005-2009 2010-2014 2015-2019     2020+ 
##         0         0       194       194       194       194         0</code></pre>
<pre class="r"><code>data2 = data %&gt;% 
  filter(quinq==&quot;2015-2019&quot;)</code></pre>
<p>Ahora sí, analicemos!</p>
<div
id="existe-una-relación-entre-la-tasa-de-fecundidad-y-el-trabajo-femenino"
class="section level3">
<h3>¿Existe una relación entre la tasa de fecundidad y el trabajo
femenino?</h3>
<p><strong>Paso 1</strong>: Exploramos variables de interés</p>
<pre class="r"><code>data2 %&gt;%
 summarize(Min = min(tfr, na.rm = TRUE),
           Media = mean(tfr, na.rm = TRUE),
           Mediana = median(tfr, na.rm = TRUE),
           Max = max(tfr, na.rm = TRUE))</code></pre>
<pre><code>##      Min    Media Mediana  Max
## 1 1.2375 2.786209 2.29875 7.21</code></pre>
<pre class="r"><code>data2 %&gt;%
 summarize(Min = min(femWork, na.rm = TRUE),
           Media = mean(femWork, na.rm = TRUE),
           Mediana = median(femWork, na.rm = TRUE),
           Max = max(femWork, na.rm = TRUE))</code></pre>
<pre><code>##    Min   Media Mediana   Max
## 1 6.03 51.9302   52.95 86.05</code></pre>
<p><strong>Paso 2</strong>: Realizamos el gráfico</p>
<pre class="r"><code>ggplot(data2, aes(x=tfr, y=femWork)) +
  geom_point(colour=&quot;skyblue&quot;) +  xlab(&quot;Tasa global de fecundidad, número promedio de hijos por mujer&quot;) +  ylab(&quot;Participación femenina en la fuerza laboral&quot;) +
  ggtitle(&quot;Relación entre la tasa de fecundidad y el trabajo femenino&quot;) +
  theme_light()+ geom_smooth(method=lm,se=F)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 15 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 15 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><strong>Paso 3</strong>: Realizamos el ANOVA</p>
<pre class="r"><code>cor.test(data2$femWork, data2$tfr)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data2$femWork and data2$tfr
## t = 1.9083, df = 177, p-value = 0.05798
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.004791544  0.282764344
## sample estimates:
##       cor 
## 0.1419805</code></pre>
<ul>
<li><p>p &lt; 0.05 Rechazas la H0 (por lo tanto, sí hay
correlación)</p></li>
<li><p>P &gt; 0.05 No rechazas la H0</p></li>
</ul>
<p>¿Qué nos dice el resultado? Recuerda que en la interpretación no debe
faltar: (i) intepretación del p-valor y (ii) interpretación del
coeficiente de correlación (cor)</p>
<p>Reporte: Dado que el p-valor es mayor a 0.05, no hay evidencia
suficiente para rechazar la H0. Por lo tanto, podemos afirmar que no
existe correlación entre el porcentaje de mujeres que trabajan y la tasa
de fecundidad</p>
</div>
<div
id="existe-una-relación-entre-la-tasa-de-fecundidad-y-el-trabajo-masculino"
class="section level3">
<h3>¿Existe una relación entre la tasa de fecundidad y el trabajo
masculino?</h3>
<pre class="r"><code>data2 %&gt;%
 summarize(Min = min(maleWork, na.rm = TRUE),
           Media = mean(maleWork, na.rm = TRUE),
           Mediana = median(maleWork, na.rm = TRUE),
           Max = max(maleWork, na.rm = TRUE))</code></pre>
<pre><code>##     Min    Media Mediana   Max
## 1 39.05 73.09888   73.95 94.75</code></pre>
<pre class="r"><code>ggplot(data2, aes(x=tfr, y=maleWork)) +
  geom_point(colour=&quot;skyblue&quot;) +  xlab(&quot;Tasa global de fecundidad, número promedio de hijos por mujer&quot;) +  ylab(&quot;Participación masculina en la fuerza laboral&quot;) +
  ggtitle(&quot;Relación entre la tasa de fecundidad y el trabajo femenino&quot;) +
  theme_light()+ geom_smooth(method=lm,se=F)</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>cor.test(data2$maleWork, data2$tfr)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data2$maleWork and data2$tfr
## t = 1.9935, df = 177, p-value = 0.04775
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.001544092 0.288582943
## sample estimates:
##       cor 
## 0.1481828</code></pre>
<p>Se puede apreciar que, al igual que con el trabajo femenino, el
p-valor es menor a 0.05, por lo que se rechaza la H0. El coeficiente es
de 0.21, lo que indica una correlación positiva pequeña.</p>
<p>Entonces, a mayor número promedio de hijos, aumenta la participación
de la fuerza laboral, tanto de hombres como mujeres. ¿Cuál podría ser
una posible explicación? Se puede pensar en la necesidad de suplir las
demandas que requieren los hijos en términos monetarios, lo que lleva a
un mayor trabajo. Se puede pensar en las políticas públicas de apoyo y
como estas permiten continuar trabajar a los padres de familia. ¿Alguna
otra posible explicación?</p>
</div>
<div
id="existe-una-relación-entre-la-tasa-de-fecundidad-y-la-esperanza-de-vida-de-las-mujeres"
class="section level3">
<h3>¿Existe una relación entre la tasa de fecundidad y la esperanza de
vida de las mujeres?</h3>
<pre class="r"><code>data2 %&gt;%
 summarize(Min = min(lifExpFem, na.rm = TRUE),
           Media = mean(lifExpFem, na.rm = TRUE),
           Mediana = median(lifExpFem, na.rm = TRUE),
           Max = max(lifExpFem, na.rm = TRUE))</code></pre>
<pre><code>##    Min    Media Mediana Max
## 1 52.6 74.16875    76.3  87</code></pre>
<p>Podemos apreciar que la esperanza de vida de las mujeres entre países
tiene un rango de 35 años entre el menor valor y el mayor. En la mayoría
de los países, este valor supera a los 76 años.</p>
<pre class="r"><code>ggplot(data2, aes(x=tfr, y=lifExpFem)) +
  geom_point(colour=&quot;skyblue&quot;) +  xlab(&quot;Tasa global de fecundidad, número promedio de hijos por mujer&quot;) +  ylab(&quot;Esperanza de vida de las mujeres&quot;) +
  ggtitle(&quot;Relación entre la tasa de fecundidad y la esperanza de vida de las mujeres&quot;) +
  theme_light()+ geom_smooth(method=lm,se=F)</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-15-1.png" width="672" />
El gráfico nos permite observar que existe una relación inversa entre
las variables, además se puede esperar que esta relación sea grande ya
que la mayoría de puntos se están ajustando a la recta que se
modela.</p>
<pre class="r"><code>cor.test(data2$tfr, data2$lifExpFem)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data2$tfr and data2$lifExpFem
## t = -21.932, df = 182, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.8871151 -0.8064711
## sample estimates:
##        cor 
## -0.8517614</code></pre>
<p>La prueba de correlación no permite comprobar lo que visualizamos en
el gráfico. Es así que obtenemos tres conclusiones principales. 1. A un
95% de confianza tenemos la evidencia suficiente para rechazar que no
haya relación entre la tasa de fecundidad y la esperanza de vida de las
mujeres en los países. 2. Esta relación es negativa, lo que implica que
en los países que tienen una tasa de fecundidad más elevada, se espera
que la esperanza de vida sea menor. 3. El coeficiente nos indica que es
una relación grande, lo que se puede ver claramente en el gráfico. Esta
relación podría explicarse por el nivel de desarrollo de algunos países
donde el acceso a servicios de salud y de educación sexual es limitado.
Esto implica que las mujeres enfrenten mayores obstáculos en cuanto a
cuidados prenatales, nutrición y/o atención médica, lo cual afecta su
salud, y así también la esperanza de vida de las mismas.</p>
</div>
<div
id="existe-una-relación-entre-la-tasa-de-fecundidad-y-el-ingreso-per-cápita-en-los-países"
class="section level3">
<h3>¿Existe una relación entre la tasa de fecundidad y el ingreso per
cápita en los países?</h3>
<pre class="r"><code>data2 %&gt;%
 summarize(Min = min(incomePp, na.rm = TRUE),
           Media = mean(incomePp, na.rm = TRUE),
           Mediana = median(incomePp, na.rm = TRUE),
           Max = max(incomePp, na.rm = TRUE))</code></pre>
<pre><code>##   Min    Media Mediana    Max
## 1 626 17798.48   11550 119750</code></pre>
<p>Para esta variable vemos aún más dispersión de los datos, ya que el
valor puede ir desde 626 dólares hasta más de 110 mil dólares.</p>
<pre class="r"><code>ggplot(data2, aes(x=tfr, y=incomePp)) +
  geom_point(colour=&quot;skyblue&quot;) +  xlab(&quot;Tasa global de fecundidad, número promedio de hijos por mujer&quot;) +  ylab(&quot;Ingreso per cápita&quot;) +
  ggtitle(&quot;Relación entre la tasa de fecundidad y el ingreso per cápita&quot;) +
  theme_light()+ geom_smooth(method=lm,se=F)</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Nuevamente, podemos esperar una relación negativa entre las
variables. En esta ocasión es más sencillo notar la presencia de los
datos atípicos.</p>
<pre class="r"><code>cor.test(data2$tfr, data2$incomePp)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data2$tfr and data2$incomePp
## t = -8.4911, df = 182, p-value = 7.085e-15
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.6288773 -0.4204107
## sample estimates:
##        cor 
## -0.5326759</code></pre>
<p>Finalmente la prueba evidencia que podemos rechazar la ausencia de
relación entre ambas variables. Y así afirmar que la tasa de fecundidad
y el ingreso per capita tienen una relación inversa, lo que quiere decir
que se espera que a medida que aumente el ingreso per capita, disminuya
la tasa de fecundidad, y viceversa. Además, esta relación es también
grande.</p>
<div id="conclusión" class="section level4">
<h4>Conclusión</h4>
<table>
<caption>Correlación entre variables y tasa de fecundidad</caption>
<thead>
<tr class="header">
<th align="left">Variables</th>
<th align="left">Coeficiente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Tasa de fec. y trabajo femenino</td>
<td align="left">No hay correlación</td>
</tr>
<tr class="even">
<td align="left">Tasa de fec. y trabajo masculino</td>
<td align="left">0.148182813219316</td>
</tr>
<tr class="odd">
<td align="left">Tasa de fec. y esperanza de vida de las mujeres</td>
<td align="left">-0.851761415467274</td>
</tr>
<tr class="even">
<td align="left">Tasa de fec. e ingreso per cápita</td>
<td align="left">-0.532675904566006</td>
</tr>
</tbody>
</table>
<p>Finalmente, podemos concluir que todas las variables analizadas se
relacionan con la tasa de fecundidad a nivel país, menos la fuerza
laboral femenina. Además, la variable que se relaciona más sería la
esperanza de vida de las mujeres, ya que su coeficiente es el más
cercano a 1, aún cuando su relación sea negativa.</p>
</div>
</div>
<div id="ejercicios-para-clase" class="section level2">
<h2>Ejercicios para clase</h2>
<ol style="list-style-type: decimal">
<li><p>¿Cómo se relaciona la tasa de fecundidad (tfr) con la equidad de
género en la educación en los países (schGenEq)?</p></li>
<li><p>¿Cómo se relaciona la tasa de fecundidad (tfr) con el porcentaje
de personas con acceso a agua en los países (water)?</p></li>
</ol>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
